import test from 'node:test';
import assert from 'node:assert/strict';
import {validateTrace,mergeTrace,requestRows,maxOverlap,traceEvents,visibleRange} from '../../Studio/model.mjs';
const event=(sequence,cat='request')=>({name:'request',cat,ph:'X',ts:sequence*10,dur:20,tid:cat==='executor'?'worker-0':'request:a',args:{requestID:'a',path:'/health',queueUS:'100'},sequence});
const doc=(seqs,sessionID='session')=>({kind:'swiftpulse.trace',schemaVersion:1,epochMS:100,sessionID,nextCursor:seqs.at(-1)??0,traceEvents:seqs.map(n=>event(n))});
test('rolling delta deduplicates and bounds memory',()=>{const a=doc([1,2,3]);const b=mergeTrace(a,doc([3,4,5]),3);assert.deepEqual(b.trace.traceEvents.map(e=>e.sequence),[3,4,5]);assert.equal(b.skipped,0);});
test('gaps and server restarts are explicit',()=>{assert.equal(mergeTrace(doc([1]),doc([4,5])).skipped,2);const restarted=mergeTrace(doc([5,6]),doc([1,2],'new'));assert.equal(restarted.restarted,true);assert.equal(restarted.trace.traceEvents.length,2);});
test('legacy snapshots replace instead of accumulating duplicates',()=>{const legacy=doc([1,2]);delete legacy.sessionID;delete legacy.nextCursor;legacy.traceEvents.forEach(e=>delete e.sequence);assert.equal(mergeTrace(legacy,legacy).trace.traceEvents.length,2);});
test('trace validation rejects malformed values and load reports',()=>{assert.throws(()=>validateTrace({kind:'pulseload.run'}));const bad=doc([1]);bad.traceEvents[0].dur=-1;assert.throws(()=>validateTrace(bad));const cursor=doc([1]);cursor.nextCursor=Infinity;assert.throws(()=>validateTrace(cursor));});
test('correlation works without a load-test run ID',()=>{const trace=doc([1]);trace.traceEvents.push(event(2,'executor'));assert.equal(requestRows(trace,'health')[0].queueMS,.1);assert.equal(traceEvents(trace,'workers','a').length,1);assert.equal(requestRows(trace,'missing').length,0);});
test('half-open intervals do not double-count touching requests',()=>{assert.equal(maxOverlap([{start:0,end:10},{start:10,end:20}]),1);assert.equal(maxOverlap([{start:0,end:20},{start:10,end:30}]),2);});
test('zoom stays in measured time range',()=>{assert.deepEqual(visibleRange([{ts:0,dur:100}],2,100),{start:50,end:100});});
